title: Project

status:
  draft:
    label: Unpublished
    text: Page is not published and doesn't appear on the website.
  listed:
    label: Published
    text: Page is published.

tabs:
  project:
    label: Texts
    icon: home
    columns:
      - width: 1/1
        sections:
          projectA:
            type: fields
            fields:
              tags:
                label: Filters
                type: multiselect
                max: 1
                options: query
                query: site.tags.toStructure.pluck("tags", ",", true)
                width: 1/2
              text:
                label: Text
                type: markdown
                width: 1/2
  material:
    label: Materials
    icon: layers
    columns:
      - width: 1/1
        sections:
          menuA:
            type: fields
            fields:
              vimeolink:
                type: url
                label: URL from the Vimeo API
                disabled: false
                icon: video
              mainImage:
                label: Background Image
                type: files
                width: 1/2
                max: 1
              # mainAudio:
              #   label: Audio file
              #   type: files
              #   width: 1/2
              #   max: 1